### ISSUE TITLE
Unexpected intellisense error message in VS2022

### ISSUE THREAD

**Issue by Zapmawww** [microsoft/proxy#103]
Hi, 
I'm using VS2022 17.10.0 with the latest MSVC toolset.
For setup, I created a windows c++ console app, then copied proxy.h to my working directory and enabled c++20 standard.
And I included proxy.h and sstream in my source, also added your example code inside the "quick start" section.

After a while, my editor reported an error of the line
`p.Draw(result);  // Polymorphic call`
with
> no instance of function template matches the argument list
> argument types are: (std::stringstream) 
> object type is: pro::proxy<<spec::Drawable>>

However, the code do compile and run with no error, and there is no error message with the call to Area(). 
`result << ", area = " << p.Area();  // Polymorphic call` <-no error reported

I am not sure if you are in charge of this bug here because I believe it is more likely an intellisense bug. Any suggestions or workarounds would be appreciated. 

Thanks.

**Comment by mingxwa** [comment]
@Zapmawww Thank you for the feedback! We have confirmed there are some false alerts from Visual C++ IntelliSense when using `proxy` in Visual Studio or VS Code IDE. While this is not an issue in `proxy` itself, I think we may need to find a minimal repro site (without the whole implementation of the library) before transferring this one to the IDE team.

**Comment by Zapmawww** [comment]
> @Zapmawww Thank you for the feedback! We have confirmed there are some false alerts from Visual C++ IntelliSense when using `proxy` in Visual Studio or VS Code IDE. While this is not an issue in `proxy` itself, I think we may need to find a minimal repro site (without the whole implementation of the library) before transferring this one to the IDE team.

@mingxwa Thanks for your reply! I am not skillful in TMP so I am afraid that I could not help much.  
However I did notice that if the dispatch contains at least one overload type that receives no parameters, for instance,
`PRO_DEF_MEMBER_DISPATCH(Draw, void(std::ostream& out), int(void))`
it will not produce the error. This also explained why the Area() is fine.
