### ISSUE TITLE
inherit member variable using proxy

### ISSUE THREAD

**Issue by MQN-80** [microsoft/proxy#117]
How do I inherit member variable if I have a Drawable class with two variable width and height, then Rectangle and circle want to inherit it

**Comment by mingxwa** [comment]
`proxy` only supports functions. It is not designed to support fields or nested types.

**Comment by MQN-80** [comment]
> `proxy` only supports functions. It is not designed to support fields or nested types.

if I want to use base class's variable,so i still need to inherit the base class ?

**Comment by mingxwa** [comment]
Assuming you are using `proxy` 2.4.0, you can define a member function (like `.size()`) or free function (like `std::size()`) to retrieve a field of a type, and wrap the functions with `PRO_DEF_MEMBER_DISPATCH` or `PRO_DEF_FREE_DISPATCH`, and define a facade with the dispatch.
