### ISSUE TITLE
Compilation error in Linux (centos8, gcc10.5)

### ISSUE THREAD

**Issue by QuantLaboratory** [microsoft/proxy#118]
/root/proxy_test/proxy.h: In member function ‘decltype(auto) pro::proxy<F>::invoke(Args&& ...) const requires requires{typename pro::details::facade_traits<F>::matched_overload<D, Args ...>;}’:
/root/proxy_test/proxy.h:690:65: error: expected ‘;’ before ‘::’ token
  690 |         MatchedOverload<D, Args...>>::template meta_provider<D>>
      |                                                                 ^
      |                                                                 ;
  691 |         ::dispatcher(ptr_, std::forward<Args>(args)...);
      |         ~~                                                       
/root/proxy_test/proxy.h:691:11: error: ‘::dispatcher’ has not been declared
  691 |         ::dispatcher(ptr_, std::forward<Args>(args)...);
      |           ^~~~~~~~~~
/root/proxy_test/proxy.h: In instantiation of ‘decltype(auto) pro::proxy<F>::invoke(Args&& ...) const requires requires{typename pro::details::facade_traits<F>::matched_overload<D, Args ...>;} [with D = MemDraw; Args = {std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&}; F = Drawable]’:

**Comment by mingxwa** [comment]
@QuantLaboratory `proxy` requires compilers to support C++20. As of now, the minimum supported GCC version is 11.2 (mentioned in [README](https://github.com/microsoft/proxy/blob/2.4.0/README.md)). Please try to update your compiler version and let us know if there is anything missing.
