### ISSUE TITLE
Where is document?

### ISSUE THREAD

**Issue by vipcxj** [microsoft/proxy#119]
The readme is wrong, the sample is wrong, the test is wrong, there is no macro PRO_DEF_MEM_DISPATCH. How to use this library?
And no pro::facade_builder as well.

**Comment by mingxwa** [comment]
The code on the main branch is not release yet. If you are consuming a specific version of `proxy`, please refer to the `README.md` of that specific version. For 2.4.0, the documentation can be found here: https://github.com/microsoft/proxy/blob/2.4.0/README.md

**Comment by vipcxj** [comment]
By the way, how to make a proxy like this:
```c++
interface Messager {
    template<typename T>
    void send(T data);
    template<typename T>
    T receive();
}
Messager m;
m.send("text");
m.send(3);
int r = m.receive();
```
I means a proxy support template method.

**Comment by mingxwa** [comment]
Due to technical limitations, `proxy` does not support template conventions. It is required to specify the signatures of each convention to create a `facade`.
