### ISSUE TITLE
A class cannot have a constructor with parameters?

### ISSUE THREAD

**Issue by QuantLaboratory** [microsoft/proxy#120]
If the constructor of a class has parameters, such as A (1), it will report an error : "<function style cast>": Unable to convert from "initializer list" to "pro:: proxy<shape>"
If there are no parameters, such as A (), it will run OK

PRO_DEF_MEM_DISPATCH(MemDraw, draw);
PRO_DEF_MEM_DISPATCH(MemPrint, print);

struct shape : pro::facade_builder
    ::add_convention<MemDraw, void()>
    ::add_convention<MemPrint, void(std::string)  noexcept>
    ::build {};

Error code snippet(If the constructor of a class has parameters) : 
std::vector<pro::proxy<shape>> shapes;

shapes.emplace_back(pro::make_proxy<shape>(rectangle(1,2)));
shapes.emplace_back(pro::make_proxy<shape>(circle(1)));

The correct code snippet(If there are no parameters) :
std::vector<pro::proxy<shape>> shapes;

shapes.emplace_back(pro::make_proxy<shape>(rectangle()));
shapes.emplace_back(pro::make_proxy<shape>(circle()));

**Comment by mingxwa** [comment]
Similar with `std::make_unique()` and `std::make_shared()`, `make_proxy()` requires a `facade` type as template parameter, i.e., `pro::make_proxy<shape>(rectangle(1,2))`. Also, `std::vector<pro::proxy>` is not a valid type, I guess you mean `std::vector<pro::proxy<shape>>`?
