### ISSUE TITLE
Poor performance? Slower than vtable?

### ISSUE THREAD

**Issue by ingangi** [microsoft/proxy#134]
I did a google benchmark test to see the difference in performance compared to vtable.

The result shows it was 2 times slower than vtable, I'm not sure if it's my test code that's at fault or if this is just the fact that performance is not something this library excels at or solves?

Reuslt:
![image](https://github.com/user-attachments/assets/9de69565-887e-41f0-b91f-36c7d290f3d1)

Benchmark code:

```cpp
#include <benchmark/benchmark.h>
#include "../proxy-main/proxy.h"
using namespace std;

// PRO_DEF_MEMBER_DISPATCH(Fun, void());
PRO_DEF_MEM_DISPATCH(MemFun, Fun);
PRO_DEF_MEM_DISPATCH(MemFun2, Fun2);
PRO_DEF_MEM_DISPATCH(MemFun3, Fun3);

struct func_proxy : pro::facade_builder
    ::add_convention<MemFun, int()>
    ::add_convention<MemFun2, int()>
    ::add_convention<MemFun3, int()>
    ::build {};

class cls1
{
public:
    int Fun()
    {
        return i;
    }
    int Fun2()
    {
        return i;
    }
    int Fun3()
    {
        return i;
    }
    int i= time(NULL);
};


class vclass
{
public:
    virtual int Fun() = 0;
    virtual int Fun2()
    {
        return i;
    }
    virtual int Fun3()
    {
        return i;
    }
    int i= time(NULL);
};
class someclass
{
public:
    int i2 = time(NULL);
};
class cls2 : public someclass, public vclass
{
public:
    virtual int Fun()
    {
        return i3;
    }
    virtual int Fun2()
    {
        return i3;
    }
    int i3 = time(NULL);
};


void use_proxy()
{
    cls1 m1;
    pro::proxy<func_proxy> msg = &m1;
    for (int i=0; i<10000; ++i)
    {
        int result = msg->Fun();
        benchmark::DoNotOptimize(result);
    }
}
void use_vtable()
{
    cls2 m2;
    vclass *pm2 = &m2;
    for (int i=0; i<10000; ++i)
    {
        int result = pm2->Fun2();
        benchmark::DoNotOptimize(result);
    }
}
void use_vtable_proxy()
{
    cls2 m2;
    vclass *pm2 = &m2;
    pro::proxy<func_proxy> msg = pm2;
    for (int i=0; i<10000; ++i)
    {
        int result = msg->Fun2();
        benchmark::DoNotOptimize(result);
    }
}


static void BM_Proxy(benchmark::State& state) {
  for (auto _ : state) {
    use_proxy();
  }
}
static void BM_Vtable(benchmark::State& state) {
  for (auto _ : state) {
    use_vtable();
  }
}
static void BM_VtableProxy(benchmark::State& state) {
  for (auto _ : state) {
    use_vtable_proxy();
  }
}

BENCHMARK(BM_Proxy);
BENCHMARK(BM_Vtable);
BENCHMARK(BM_VtableProxy);

BENCHMARK_MAIN();
```

**Comment by ingangi** [comment]
Update:
When I change the loop count from 10000 to 10, the result changed, proxy is faster.
![image](https://github.com/user-attachments/assets/61e1865b-1ee2-4bea-8529-f086088a1dbf)

**Comment by mingxwa** [comment]
@ingangi Could you share more context about the compiler version, flags and your test environment? Any template library, including STL implementations requires compiler optimizations to generate high quality code. If compiler optimization is properly set, I guess all the indirect calls in your code will be optimized away, because the implementation is in the same compilation unit. I suggest reviewing the generated code via [Compiler Explorer](https://godbolt.org/).

**Comment by ingangi** [comment]
@mingxwa thank you for the quick response. 
compiler: `g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`
flags: `-std=c++20 -O2 -isystem benchmark/include -Lbenchmark/build/src -lbenchmark -lpthread`

**Comment by mingxwa** [comment]
@ingangi I tried to compile your code with GCC 11.4, and observed that the virtual function calls in `use_vtable()` are devertualized, but not devertualized in `use_proxy()` and `use_vtable_proxy()`. See the screenshots below:

![image](https://github.com/user-attachments/assets/c025a775-37da-4ca7-9e07-7e3e2af01f13)
![image](https://github.com/user-attachments/assets/049c2804-b325-450f-999d-3da5c92f5c15)

Indeed, GCC is better at devertualizing native virtual functions than `proxy` in this case. However, in most scenarios, runtime abstraction is used accross translation units or even ABI boundaries, and there is little chance for devirtualization. I think it would be more reasonable for the benchmark to separate the abstraction and implementation into different translation units, and see how it goes. From my personal experience, the numbers shoule be similar.

**Comment by tan-wei** [comment]
> Update: When I change the loop count from 10000 to 10, the result changed, proxy is faster. ![image](https://private-user-images.githubusercontent.com/9778842/351929128-61e1865b-1ee2-4bea-8529-f086088a1dbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDU5NjEsIm5iZiI6MTcyNTYwNTY2MSwicGF0aCI6Ii85Nzc4ODQyLzM1MTkyOTEyOC02MWUxODY1Yi0xZWUyLTRiZWEtODUyOS1mMDg2MDg4YTFkYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDY1NDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc1ZDVmYTIyNGU0YWFjOGJlNGNkY2E0MTNjOTM2ZTFjYzhhYWVkMzYxZmJiZmFhYWU4YTU3NWE5MDc2YTYwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GhxqjGskn72HlmWNnXWfLAQ0bEOBkw2hfIBmn56z61M)

acctually, on my side with just the same code, vptr is still faster:
```
2024-09-06 15:15:16
Running build/benchmark/benchmarks
Run on (4 X 2419.2 MHz CPU s)
CPU Caches:
  L1 Data 48K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 1280K (x4)
  L3 Unified 8192K (x4)
Load Average: 2.16, 3.58, 4.76
------------------------------------------------------
Benchmark               Time           CPU Iterations
------------------------------------------------------
BM_Proxy               18 ns         18 ns   40740186
BM_Vtable               8 ns          7 ns   93556693
BM_VtableProxy         27 ns         26 ns   26204758
```
The GCC version is 14.2.1, and with the latest version of `proxy` [[e0846a5](https://github.com/microsoft/proxy/commit/e0846a5547643f9f235f3fdad4e2eb3d4991761c).
