### ISSUE TITLE
How to create a class that does not contain all the signature definition functions?

### ISSUE THREAD

**Issue by MoFHeka** [microsoft/proxy#140]
For example:
```C++
void default() {
  throw std::runtime_error("No Implement!"); 
}

PRO_DEF_MEM_DISPATCH(MemDraw, Draw, Draw, default);

struct Drawable : pro::facade_builder
    ::add_convention<MemDraw, 
                    void(std::ostream& output, type custom_num),
                    void(std::ostream& output>
    ::build {};

// A class without method  void(std::ostream& output, type custom_num)
template<typename T>
class Rectangle {
 public:
  void Draw(std::ostream& out) const
      { out << "{Rectangle: width = " << width_ << ", height = " << height_  << "}"; }
  void SetWidth(T width) { width_ = width; }
  void SetHeight(T height) { height_ = height; }
  T Area() const { return width_ * height_; }

 private:
  T width_;
  T height_;
};
```
The default implementation is called when the class Rectangle does not implement another function signature.

**Comment by mingxwa** [comment]
@MoFHeka

Looks like you are using the code on main branch. Note that main branch is in active development and contains undocumented features (as of now) to be included in the next major release (3.0). Here is how you can define a "weak" dispatch (which means a dispatch with a default implementation) with 3.0 syntax `PRO_DEF_WEAK_DISPATCH`. Please make sure you have the latest code on main branch to compile the following code.

```cpp
#include <iostream>

#include "proxy.h"

struct NotImplemented {
  explicit NotImplemented(auto&&...) { throw std::runtime_error{ "Not implemented!" }; }

  template <class T>
  operator T() const noexcept { std::terminate(); }  // Or std::unreachable() in C++23
};

PRO_DEF_MEM_DISPATCH(MemDraw, Draw);
PRO_DEF_WEAK_DISPATCH(WeakMemDraw, MemDraw, NotImplemented);

struct Drawable : pro::facade_builder
    ::add_convention<WeakMemDraw,
        void(std::ostream& output, int custom_num),
        void(std::ostream& output)>
    ::build {};

struct Foo {
  void Draw(std::ostream& out) const { out << "Foo\n"; }
};

int main() {
  Foo foo;
  pro::proxy<Drawable> p = &foo;
  p->Draw(std::cout);
  try {
    p->Draw(std::cout, 123);  // Throws
  } catch (const std::runtime_error& e) {
    puts(e.what());  // Prints: "Not implemented!"
  }
}
```

**Comment by MoFHeka** [comment]
May I ask when version 3.0 will be released?

**Comment by mingxwa** [comment]
> May I ask when version 3.0 will be released?

I can't guarantee the timeline, but presumably in August, while we are still working on the documentation. Please stay tuned 😉

> And Is the default implementation of PRO_DEF_WEAK_DISPATCH only supporting struct constructors and not a function that returns a value?

No. The semantics is the same as the `_WITH_DEFAULT` syntax in 2.4. It can take the name of an arbitrary function or anything that supports `()` syntax, including a constructor.
