### ISSUE TITLE
pro::proxy<Drawable> obj may reconstruct class when it's a function return value unless using make_proxy.

### ISSUE THREAD

**Issue by MoFHeka** [microsoft/proxy#141]
For example:
```C++
pro::proxy<Drawable> CreateRectangleAsDrawable(int width, int height) {
  Rectangle<int> rect;
  rect.SetWidth(width);
  rect.SetHeight(height);
  pro::proxy<Drawable> p = &rect;
  return std::move(p);
}
```
Unless use 
```C++
return pro::make_proxy<Drawable>(rect)
```
Isn't that a little unfriendly?

**Comment by mingxwa** [comment]
Your example is incorrect. `proxy` holds any pointer you create with, i.e., if you create a `proxy` with a raw pointer, it just behaves like a raw pointer and does not take ownership of the object. In your example, `p` holds a raw pointer to a temporary, and becomes dangling after the function returns.

`make_proxy` behaves like `std::unique_ptr` but more powerful (can be copied / avoid heap allocation). It takes ownership of the object. If you want to avoid copy when calling `make_proxy`, it is encouraged to use in-place construction instead, e.g.,`make_proxy<Drawable, Rectangle>(width, height)` (given that `Rectangle` has an applicable constructor).

**Comment by MoFHeka** [comment]
Thanks for your reply

**Comment by MoFHeka** [comment]
@mingxwa  How can I forward the constructing method implementation to another container if I want a deferring class. creation?

**Comment by mingxwa** [comment]
> How can I forward the constructing method implementation to another container if I want a deferring class creation?

This looks like a design question. I guess you might want something like a "factory":

```cpp
PRO_DEF_MEM_DISPATCH(MemCreate, Create);

template <class F, class... Args>
struct Factory : pro::facade_builder
    ::add_convention<MemCreate, pro::proxy<F>(Args...)>
    ::build {};
```

> how to access SetWidth(width) through proxy after make_proxy<Drawable, Rectangle>(width, height) created? Only add_convention?

It depends on when the `SetWidth` is called. If it is called before type erasure, the facade does not need the knowledge. With the `Factory` defined above, implementations can do anything in a `Create` function, not limited to `SetWidth`. For example:

```cpp
struct Printable : pro::facade_builder
    ::add_convention<pro::operator_dispatch<"<<", true>, std::ostream&(std::ostream& out) const>
    ::build {};

class MyIntFactory {
 public:
  explicit MyIntFactory(int val) : val_(val) {}
  pro::proxy<Printable> Create() { return pro::make_proxy<Printable>(val_++); }

 private:
  int val_;
};

int main() {
  pro::proxy<Factory<Printable>> factory = pro::make_proxy<Factory<Printable>, MyIntFactory>(3);
  pro::proxy<Printable> p1 = factory->Create();
  pro::proxy<Printable> p2 = factory->Create();
  std::cout << *p1 << "\n";  // Prints: "3"
  std::cout << *p2 << "\n";  // Prints: "4"
}
```
