### ISSUE TITLE
Can/recommend proxy be used across dll boundary?

### ISSUE THREAD

**Issue by heroboy** [microsoft/proxy#156]
1. What if dll and exe use different proxy.h verison?
    Is there any compatibility proxy can ensure?
2. Will `make_unique`/`make_proxy` result allocate memory in exe and free in dll?
3. Can proxy manage COM object lifetime? Call `Release` when it destroyed.

**Comment by mingxwa** [comment]
1. It is usually compatible for a same major version (like 2.0.0 and 2.1.0), but not compatible for different major versions (like 2.0 and 3.0.0-rc1).
2. It is supported, like any smart pointer.
3. Sure. The behavior depends on the implementation of the given pointer type, e.g., you can use [`winrt::com_ptr`](https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/com-ptr) to instantiate a `proxy`.

**Comment by heroboy** [comment]
Thank you.

But for 2, I think it is not like `std::unique_ptr<T>`, but like `std::shared_ptr<T>`

**Comment by mingxwa** [comment]
For 2, if you assign a `std::unique_ptr` to a `proxy`, the `proxy` object will have the same behavior with `std::unique_ptr`.

**Comment by heroboy** [comment]
okok.

> But for 2, I think it is not like std::unique_ptr<T>, but like std::shared_ptr<T>

I mean you should not export a function in dll like `void foo(std::unique_ptr<SomeObject> obj)`. Because `obj` will be destruct in the dll side.

> For 2, if you assign a `std::unique_ptr` to a `proxy`, the `proxy` object will have the same behavior with `std::unique_ptr`.

This word is misleading. `proxy` is very different than the `std::unique_ptr`, it will create and stored enough meta data. The destruction of `std::unique_ptr` and the obj stored in `std::unique_ptr` will happen in the exe side(the place where the proxy constructed).

Like the `std::shared_ptr` will store a function how to destroy the object.
