### ISSUE TITLE
In which occasion we should use proxy than old style polymorphic?

### ISSUE THREAD

**Issue by lushengguo** [microsoft/proxy#162]
I just found this repo on github and didn't get the advantage about it, can you give me some example that 'proxy' is far more convinient that old style polymorphic?

**Comment by frederick-vs-ja** [comment]
First of all, this is not an issue and should go to "Discussions".

The major convenience, IMO, is that "proxy" is non-intrusive, so we don't need to change the representation of our types to achieve polymorphic behavior. Non-intrusive type erasure can also be achieved via (native) virtual functions, but such an approach sometimes needs more indirection (dereferencing) and is less performant.

**Comment by mingxwa** [comment]
It is generally recommended to use the "Proxy" library over virtual functions if your compiler supports C++20. Although virtual functions can be used to implement runtime polymorphism, they can lead to significant work when the architecture changes and can make memory management deficient when there are many small objects. Please refer to the [FAQ](https://microsoft.github.io/proxy/docs/faq.html#who-is-proxy-for).
