### ISSUE TITLE
Fail to download proxy-1.1.1 from vcpkg

### ISSUE THREAD

**Issue by psudo9** [microsoft/proxy#214]
When installing proxy-1.1.1 from vcpkg, got following error:

2>-- Downloading https://github.com/microsoft/proxy/archive/release/1.1.1.tar.gz -> microsoft-proxy-release_-1.1.1.tar.gz...
2>[DEBUG] To include the environment variables in debug output, pass --debug-env
2>[DEBUG] Trying to load bundleconfig from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\vcpkg-bundle.json
2>[DEBUG] Bundle config: readonly=true, usegitregistry=true, embeddedsha=2960d7d80e8d09c84ae8abf15c12196c2ca7d39a, deployment=VisualStudio, vsversion=17.0/
2>[DEBUG] VS telemetry opted in at SOFTWARE\WOW6432Node\Microsoft\VSCommon\17.0\SQM\\OptIn
2>[DEBUG] Metrics enabled.
2>[DEBUG] Feature flag 'binarycaching' unset
2>[DEBUG] Feature flag 'compilertracking' unset
2>[DEBUG] Feature flag 'registries' unset
2>[DEBUG] Feature flag 'versions' unset
2>[DEBUG] Feature flag 'dependencygraph' unset
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: Missing microsoft-proxy-release_-1.1.1.tar.gz and downloads are blocked by x-block-origin.
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://github.com/microsoft/proxy/archive/release/1.1.1.tar.gz: failed: status code 404

**Comment by mingxwa** [comment]
We noticed that before version 2.0.0, vcpkg uses `release/${VERSION}` as the baseline of a version, which is no longer supported by the `proxy` repo. Unfortunately, we can't fix earlier versions from vcpkg, but newer versions (2.0.0 and above) should work fine.
