### ISSUE TITLE
Storing pro::proxy<T> in container and iteration

### ISSUE THREAD

**Issue by pr0g** [microsoft/proxy#25]
Hi there,

I really like the look of this library, it seems like a very interesting idea.

One thing I might be missing is how to mimic the classic `std::vector<Base*>` polymorphic iteration where you might have something like...

```c++
std::vector<IDrawable>* drawables;

// ... add different types of derived drawables...

for (auto* drawable : drawables) {
    drawable->Draw(...);
}
```

(example types taken from https://devblogs.microsoft.com/cppblog/proxy-runtime-polymorphism-made-easier-than-ever/)

When I try this with the library it compiles...

```c++
std::vector<pro::proxy<DrawableFacade>> drawables;

Rectangle rect(100, 200);
Circle circle(50);

drawables.push_back(&rect);
drawables.push_back(&circle);
```

But when I try to do this...

```c++
for (auto drawable : drawables) {
    PrintDrawableToString(drawable);
}
```

I get the compile error...

```
error: call to deleted constructor of 'pro::proxy<DrawableFacade>'
```

Is there a means to do this using `proxy` or would you recommend a different approach? (I know the example is pretty contrived and usually these days you don't want to do that anyway because of the pointer indirection and likely poor cache locality but I was just curious if you could write something similar using `proxy`).

Thanks very much for your time!

**Comment by mingxwa** [comment]
@pr0g This code won't compile because it requires implicit copy construction, but `proxy` is not copy-constructible with the default configuration of `facade`.

There are two ways to fix the code:
1. use reference semantics instead of value semantics when enumerating the elements in the container (i.e., `auto&` instead of `auto`), or
2. make `proxy` copy-constructible by specifying `minimum_copyability = pro::constraint_level::nontrivial` in the `facade` definition (see [Highlight 7 in the blog post](https://devblogs.microsoft.com/cppblog/proxy-runtime-polymorphism-made-easier-than-ever/#highlight-7-performance-tuning)), at the cost that the `proxy` is no longer constructible from non-copyable pointer types like `std::unique_ptr`.

**Comment by pr0g** [comment]
Thank you very much for the reply and explanation @mingxwa.

Regarding point 1, I was viewing the `proxy` type as a view-like object (similar to `string_view` or `span`, which you always pass by value), but it seems this is not entirely true and treating it more like the object itself makes more sense (I'm curious what would be the mental model you'd recommend for `proxy` types?). As a side note, in the `for` loop example is it possible to use `const auto&` if you know the member functions being called through `invoke` are themselves const or is it required to use `auto&`? (I hit the compile error `error: no matching member function for call to 'invoke'` when trying to use `const auto&`).

Point 2 is interesting and may be more appropriate for my use case. If you're dealing with POD types would you recommend this approach (should you override the constraints often or would you recommend using the defaults as much as possible?).

Thanks again for the info and I look forward to playing around with the library more.

Cheers!

**Comment by pr0g** [comment]
About the `const` question I just spotted your answer here - https://github.com/microsoft/proxy/issues/24#issuecomment-1221732273 which partly answers my question.

Could you clarify what you mean when you say "_it is encouraged to pass parameters by pointer_", would you be able to give an example of this, please? Do you mean `void some_function(pro::proxy<DrawableFacade>* drawableFacade)` or something else?

Thanks again for your time

**Comment by mingxwa** [comment]
> Regarding point 1, I was viewing the proxy type as a view-like object (similar to string_view or span, which you always pass by value), but it seems this is not entirely true and treating it more like the object itself makes more sense.

Yes. `proxy` is not a view of a pointer. It **has a** pointer. If you want to `invoke` on a "proxy", it is required not to use `const`.

> If you're dealing with POD types would you recommend this approach (should you override the constraints often or would you recommend using the defaults as much as possible?).

If we are confident that the `proxy` is always instantiated with a POD type (like a raw pointer), and want to optimize the performance to the limit, it is allowed to reduce `maximum_size` and add more constraints to the required capabilities (see [Highlight 7 in the blog post](https://devblogs.microsoft.com/cppblog/proxy-runtime-polymorphism-made-easier-than-ever/#highlight-7-performance-tuning)):

```cpp
// Abstraction
struct MyFacade : pro::facade</* Omitted */> {
  static constexpr auto minimum_copyability = pro::constraint_level::trivial;
  static constexpr auto minimum_relocatability = pro::constraint_level::trivial;
  static constexpr auto minimum_destructibility = pro::constraint_level::trivial;
  static constexpr auto maximum_size = sizeof(void*);
  static constexpr auto maximum_alignment = alignof(void*);
};

// Client
static_assert(std::is_trivially_copy_constructible_v<pro::proxy<MyFacade>>);
static_assert(std::is_trivially_destructible_v<pro::proxy<MyFacade>>);
```

> Could you clarify what you mean when you say "it is encouraged to pass parameters by pointer", would you be able to give an example of this, please? Do you mean void some_function(pro::proxy<DrawableFacade>* drawableFacade) or something else?

Yes, I mean `void some_function(pro::proxy<DrawableFacade>* drawable)`, as long as "drawable" is not a sink argument. However, it is not a general guidance of C++. You can also use lvalue references if compatible with your team's coding guidelines.

**Comment by pr0g** [comment]
Thank you for the reply and clarifications @mingxwa, the information is super helpful.

I've been mulling it over and I do think not being able to distinguish `const` interfaces is a problem for adoption. Would it be possible to provide an overload of `invoke` that is `const` or even have an explicit `invoke_const` users could call? I just think having a `const proxy<T>&` parameter could be very helpful for code maintenance reasons (to know immediately the underlying object is not being mutated and all `dispatch` functions must be `const`).

The library is still super cool and I'll definitely spend some more time playing around with it, I just miss not being able to add `const` to everything 😝

Thanks again for your help!

**Comment by mingxwa** [comment]
@pr0g Thank you for your valuable comments! We decided to add more constraints to pointer types that are eligible to proxy, requiring dereference from a const lvalue reference, so that we can add `const` qualifier to `proxy::invoke()`. I filed [PR 28](https://github.com/microsoft/proxy/pull/28). Does this change look good to you?

**Comment by pr0g** [comment]
> @pr0g Thank you for your valuable comments! We decided to add more constraints to pointer types that are eligible to proxy, requiring dereference from a const lvalue reference, so that we can add `const` qualifier to `proxy::invoke()`. I filed [PR 28](https://github.com/microsoft/proxy/pull/28). Does this change look good to you?

Hi @mingxwa,

My pleasure and that is absolutely fantastic to hear! 😄 Thank you so much for making it possible to add `const`, I'll take a look at [PR 28](https://github.com/microsoft/proxy/pull/28) shortly and leave a comment there.

Thanks again, I really appreciate you looking into this and I'm delighted I can continue to `const` all the things! 😅 🙂

**Comment by pr0g** [comment]
I just tested out the latest build but now unfortunately I think we have the opposite problem I'm afraid 😅 

Here's a snippet of the code I have (based on the examples from the blogpost)

```c++
struct Draw : pro::dispatch<void(std::ostream&)> {
  template<class T>
  void operator()(const T& self, std::ostream& out) {
    self.Draw(out);
  }
};

struct Area : pro::dispatch<double()> {
  template<class T>
  double operator()(const T& self) {
    return self.Area();
  }
};

// my addition - see this is non-const and mutates the underlying object
struct Grow : pro::dispatch<void()> {
  template<class T>
  void operator()(T& self) {
    self.Grow();
  }
};

// as this is composed of both const and non-const operations, you should
// only be allowed to use this with a non-const pointer/reference/object
struct DrawableFacade : pro::facade<Draw, Area, Grow> {};

class Rectangle {
public:
  Rectangle() = default;
  Rectangle(double width, double height) : width_(width), height_(height) {}
  void Draw(std::ostream& out) const {
    out << "{Rectangle: width = " << width_ << ", height = " << height_ << "}";
  }
  Rectangle(const Rectangle& rectangle) = default;
  void SetWidth(double width) { width_ = width; }
  void SetHeight(double height) { height_ = height; }
  double Area() const { return width_ * height_; }
  void Grow() {
    width_ *= 2.0;
    height_ *= 2.0;
  }

private:
  double width_;
  double height_;
};

class Circle {
public:
  Circle() = default;
  Circle(double radius) : radius_(radius) {}
  void Draw(std::ostream& out) const {
    out << "{Circle: radius = " << radius_ << "}";
  }
  Circle(const Circle& Circle) = default;
  void SetRadius(double radius) { radius_ = radius; }
  double Area() const { return radius_ * 3.142 * 3.142; }
  void Grow() { radius_ *= 2.0; }

private:
  double radius_;
};

// because this proxy is const, p.invoke<Grow>() (in my mind at least) should fail
// to compile, as we're mutating the object, but right now this compiles just fine,
// event though the proxy is marked const
std::string PrintDrawableToString(const pro::proxy<DrawableFacade>& p) {
  std::stringstream result;
  result << "shape = ";
  p.invoke<Draw>(result);
  p.invoke<Grow>();
  result << ", area = " << p.invoke<Area>();
  return std::move(result).str();
}

pro::proxy<DrawableFacade> CreateRectangleAsDrawable(int width, int height) {
  Rectangle rect;
  rect.SetWidth(width);
  rect.SetHeight(height);
  return pro::make_proxy<DrawableFacade>(rect);
}

int main(int argc, char** argv) {
  Rectangle rect(100, 200);
  Circle circle(50);

  std::vector<pro::proxy<DrawableFacade>> drawables;
  drawables.push_back(&rect);
  drawables.push_back(&circle);

  for (const auto& drawable : drawables) {
    std::cout << PrintDrawableToString(drawable) << "\n";
  }

  return 0;
}
```

Please see my comments inline for details, so I now think this might potentially be worse than before, as something that appears to be const, can also be mutated, which could be very surprising to clients 🤔 Is there a way to get the best of both worlds? So we can have a const-only facade that you can use `const pro::proxy<T>&` with but it forces you to use `pro::proxy<T>& p` if the facade has mutating operations?

Also for completeness, my `CMakeLists.txt` file looks like this...

```cmake
cmake_minimum_required(VERSION 3.15)
project(proxy-example LANGUAGES CXX)

include(FetchContent)

FetchContent_Declare(
  proxy
  GIT_REPOSITORY https://github.com/microsoft/proxy.git
  GIT_TAG 0b5ecfab3877f1f57df633bb0e68c8c4111bfd86)

FetchContent_MakeAvailable(proxy)

add_executable(${PROJECT_NAME})
target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_20)
target_link_libraries(${PROJECT_NAME} PRIVATE msft_proxy)
target_sources(${PROJECT_NAME} PRIVATE main.cpp)
```

**Comment by mingxwa** [comment]
@pr0g 

> Please see my comments inline for details, so I now think this might potentially be worse than before, as something that appears to be const, can also be mutated, which could be very surprising to clients 🤔

A `const proxy` represents a `const` pointer. Whether the pointee is `const` depends on the type of the pointer. For example, if we construct a `proxy` with `int*`, invoking any dispatch adds `const` to `int*`, i.e. `int* const` rather than `const int*`.

> because this proxy is const, p.invoke<Grow>() (in my mind at least) should fail to compile, as we're mutating the object, but right now this compiles just fine, even though the proxy is marked const

Similarly, one could always mutate the value pointed by `const unique_ptr<int>` no matter using `proxy` or not.

> ```cpp
> // as this is composed of both const and non-const operations, you should
> // only be allowed to use this with a non-const pointer/reference/object
> struct DrawableFacade : pro::facade<Draw, Area, Grow> {};
> ```

This definition implies that the pointee should be non-const, rather than the pointer. For example, it won't compile if we construct a `proxy<DrawableFacade>` with `const Rectangle*`.

**Comment by pr0g** [comment]
Hi @mingxwa, thank you for the reply. I see that makes sense. Is there the facility to then write...

```
std::string PrintDrawableToString(const pro::proxy<const DrawableFacade>& p) {
    ...
}
```

...so the template argument can be marked `const` to indicate it cannot be mutated (similar to how `std::span` works where we would use `void doSomething(std::span<const T> values)` to indicate the contained elements cannot be mutated?

**Comment by mingxwa** [comment]
@pr0g 

> ...so the template argument can be marked const to indicate it cannot be mutated (similar to how std::span works where we would use void doSomething(std::span<const T> values) to indicate the contained elements cannot be mutated?

Different from `std::span`, `proxy` is not a *view*. The underlying object will not be mutated as long as `*p` represents a const reference, where `p` is the underlying pointer. For example, you can construct a `proxy` with `std::unique_ptr<const Foo>` to ensure the underlying object of type `Foo` shall never be mutated, if necessary.
