### ISSUE TITLE
Differentiate interface abstraction from const member function

### ISSUE THREAD

**Issue by coyorkdow** [microsoft/proxy#37]
The member functions have same name, same parameters, and same return type, but with or without const qualifier, are regarded as two different functions. A class can has both two functions while one is virtual and another isn't. In proxy's design, an interface is identified by the template paramters of the base class `pro::dispatch` and the struct inherited the base. We cannot determine const or non-const through the interface definition.

I noticed that all the `self` operands are defined with the const qualified in both document and sample/unittests. In this way we can restrict the interface must be a const member function. If remove the const, then it's equivalent to define the interfaces for both const and non-const member functions. What we cannot do is define the interface to the non-const function only.

There is a possilble approach that differentiate between const and non-const by defining the `operator()` as const or non-const.

**Comment by mingxwa** [comment]
Thank you for the suggestion @coyorkdow. Actually, `proxy` already has the capability to differentiate `const` and non-`const` expressions, but in a different form from traditional (inheritance-based) polymorphism. Specifically, traditional one requires `const` on the base type while using it (client shall have the knowledge of `const`-ness to use a polymorphic object correctly), while `proxy` only requires `const` when constructing it (client no longer needs this information anymore, making the API boundary clean).

For example:

```cpp
#include <cstdio>
#include <memory>

#include <proxy.h>

struct FooDispatch : pro::dispatch<void()> {
  template <class T>
  void operator()(T& value) const {
    value.Foo();
  }
};
struct FooFacade : pro::facade<FooDispatch> {};

struct MyFooStruct {
  void Foo() { puts("Non-const Foo()"); }
  void Foo() const { puts("Const Foo()"); }
};

int main() {
  pro::proxy<FooFacade> p1 = std::make_unique<MyFooStruct>();
  pro::proxy<FooFacade> p2 = std::make_unique<const MyFooStruct>(); // `p1` and `p2` are of the same type
  p1.invoke(); // prints "Non-const Foo()"
  p2.invoke(); // prints "Const Foo()"
  return 0;
}
```

**Comment by coyorkdow** [comment]
> Thank you for the suggestion @coyorkdow. Actually, `proxy` already has the capability to differentiate `const` and non-`const` expressions, but in a different form from traditional (inheritance-based) polymorphism. Specifically, traditional one requires `const` on the base type while using it (client shall have the knowledge of `const`-ness to use a polymorphic object correctly), while `proxy` only requires `const` when constructing it (client no longer needs this information anymore, making the API boundary clean).
> 
> For example:
> 
> ```c++
> #include <cstdio>
> #include <memory>
> 
> #include <proxy.h>
> 
> struct FooDispatch : pro::dispatch<void()> {
>   template <class T>
>   void operator()(T& value) const {
>     value.Foo();
>   }
> };
> struct FooFacade : pro::facade<FooDispatch> {};
> 
> struct MyFooStruct {
>   void Foo() { puts("Non-const Foo()"); }
>   void Foo() const { puts("Const Foo()"); }
> };
> 
> int main() {
>   pro::proxy<FooFacade> p1 = std::make_unique<MyFooStruct>();
>   pro::proxy<FooFacade> p2 = std::make_unique<const MyFooStruct>(); // `p1` and `p2` are of the same type
>   p1.invoke(); // prints "Non-const Foo()"
>   p2.invoke(); // prints "Const Foo()"
>   return 0;
> }
> ```

I see. So from my understanding of this explanation, regarding const and non-const as two different interfaces is somehow a drawback due to the limitation of the inheritance-base polymorphism. The design of the proxy is remove the const semantics on interface level while the client freely chose whether it is const or not.

Am I right? Thank you.

**Comment by mingxwa** [comment]
@coyorkdow Yes, I believe so.
