### ISSUE TITLE
[FR] Add std::function_ref equivalent functionality

### ISSUE THREAD

**Issue by psiha** [microsoft/proxy#65]
A 'proxy_ref': so that we don't pass around `proxy const &` (thereby incurring a double indirection).

**Comment by mingxwa** [comment]
If I understand correctly, `proxy` already provides the capability. You can simply instantiate a `proxy<F>` with any raw pointer type `P` (although `proxy<F>` still has nontrivial move ctor and dtor, it behaves like a raw pointer).

If `proxy<F>` is intended not to take any ownership for all `P`, it is allowed to fine tune performance like `std::function_ref` does. Lifetime semantics is associated with the definition of a facade (`F::constraints`). If you are using `PRO_DEF_FACADE` to define a facade, the constraints can be specified on the 3rd parameter, e.g.,

```cpp
PRO_DEF_MEMBER_DISPATCH(Draw, void(std::ostream& out));
PRO_DEF_FACADE(DrawableRef, Draw, pro::trivial_ptr_constraints);
```

`proxy<DrawableRef>` will have trivial copy ctor and move ctor, but it can no longer hold any smart pointers (e.g., `std::unique_ptr` `std::shared_ptr` or `pro::details::sbo_ptr`).

**Comment by psiha** [comment]
That's not the same: a function_ref-like thingy does not need an SBO (or heap allocation) for any kind of target object - as it references it directly (as opposed to owning it) - it can/should be able to bind to a temprary (function argument).
A reference to a trivial proxy<> has two indirections: reference to the proxy and then a reference to the vtable (and possibly an additional one to the target if it did not fit into the SBO storage).
trivial_ptr_constraints will make proxy the size of two pointers, like function_ref but will require a heap allocation and a nontrivial destructor for larger-than-a-pointer targets _or_ not support those at all.

**Comment by mingxwa** [comment]
> trivial_ptr_constraints will make proxy the size of two pointers, like function_ref but will require a heap allocation and a nontrivial destructor for larger-than-a-pointer targets or not support those at all.

In the design of `proxy`, if `trivial_ptr_constraints` is specified in a `facade` definition `F`, `proxy<F>` is a trivial type. It is covered in our [unit tests](https://github.com/microsoft/proxy/blob/main/tests/proxy_traits_tests.cpp#L122-L144).

**Comment by mingxwa** [comment]
The dereferencing of small vtable is triaged as a QoI issue (filed !69).
