### ISSUE TITLE
readme overload demo forgot update?

### ISSUE THREAD

**Issue by lty123456** [microsoft/proxy#95]
readme overload demo can not compiled in my vs22 cmake c++20

i had to update these code:
logger.Log("hello");  and logger.Log("world", e);
to:
logger.invode<spec::Log>("hello"); and logger.invode<spec::Log>("world", e);
to compile

**Comment by mingxwa** [comment]
@lty123456 Thank you for the feedback! May I know which version of `proxy` and MSVC are you using?

**Comment by lty123456** [comment]
sorry,   i pull this rep fail yesterday, demo is ok now.

另外我希望将proxy和信号槽库[sigslot](https://github.com/palacaze/sigslot)一起用，但是信号连接时碰到一些问题：
sigslot库连接时需要提供槽函数的函数指针，但不知道如何获取与PRO_DEF_MEMBER_DISPATCH定义时参数类型一致的指针，例如：

PRO_DEF_MEMBER_DISPATCH(DrawFloat, void(T1), void(T2, T3));
void(pro::proxy<FDrawable>:: * M2)(T1) const = &pro::proxy<FDrawable>::template invoke < DrawFloat >;

,如上：T1是在PRO_DEF_MEMBER_DISPATCH定义时的参数类型，尝试获取这个函数指针M2时，只有当T1类型是左值引用（信号系统存在一对多可能不用考虑右值引用）float&或const float&才能编译，如果是float或const float则编译失败，但是可以通过把第二行的T1改成const float&类型如：
void(pro::proxy<FDrawable>:: * M2)(const float&) const = &pro::proxy<FDrawable>::template invoke < DrawFloat >;来编译，这样其实也还好，可以通过编写中间模板自动将非引用类型参数转接到常量引用，但是麻烦的是参数个数是变长的，需要对每个参数进行处理目前没有思路，不知是否能给予相关指导，或者有没有办法能获取到与PRO_DEF_MEMBER_DISPATCH定义一致的函数指针就不需要针对T1、T2、T3...等做类型转换了

这是我目前更完整的测试代码：https://godbolt.org/z/e9YxeYv9b，第9-11行自动参数类型T1、T2、T3的取值不能取FT1、FT2，除非配合修main中对应参数类型为const&

**Comment by mingxwa** [comment]
@lty123456 Why using member function pointers rather than lambda expressions? Something like `sigVoid.connect([&f] { f.Draw(); });`?

To obtain the address of `proxy::invoke()`, note that it is a function template that has variadic template arguments except for the first "dispatch":

```cpp
template <class D = DefaultDispatch, class... Args>
decltype(auto) invoke(Args&&... args) const;
```

**Comment by lty123456** [comment]
相对来说lambda会不会多加一层运行时开销？我还是刚使用这两个库，也不知道更深层的东西、使用边界在哪

**Comment by lty123456** [comment]
我目前可以用这种方式来实现Connect：
template <typename MethodT, typename... Args, typename SignalT, typename FacadeT>
auto Connect(SignalT& signal, FacadeT* facade)
{
    void(FacadeT:: * T)(Args...) const = &FacadeT::template invoke<MethodT>;
    return signal.connect(T, facade);
}

template <typename MethodT, typename... Args, typename FacadeT>
auto Connect(sigslot::signal<Args...>& signal, FacadeT* facade)
{
    void(FacadeT:: * T)(Args...) const = &FacadeT::template invoke<MethodT>;
    return signal.connect(T, facade);
}
加了个手动指定参数的模板，这样在无法自动匹配时可以手动匹配如：
using T1 = FT1;
using T2 = FT2;
using T3 = FT4;
/*... ignore
    Connect <Draw> (sigVoid, &f);
    Connect <DrawFloat, const float&>(sigFloat, &f);
    Connect <DrawFloat, const float&, float&> (sigFloatFloat, &f);

**Comment by mingxwa** [comment]
@lty123456 I think lambda expressions should be preferred in this scenario. Compilers are expected to be smart enough to optimize code generation when asked to (you can specify /O2 in MSVC). You should be able to inspect the generated code with Compiler Explorer, and I assume the generated code should be similar with the function pointer version.

**Comment by lty123456** [comment]
原来如此，感谢解答

**Comment by vipcxj** [comment]
@mingxwa proxy只能接受指针或类似指针的东西？例子中lambda没有直接当参数，而是先取地址后再当参数传给proxy，那是不是意味这lambda的所有权没有传给proxy？这样生命周期不好管理啊。另外看了那个设计文档，proxy好像可以接受shared_ptr，还支持weak_ptr，有没有具体例子？现有例子太简单了。
